package dev.chpg.pg.global;

import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import dev.chpg.pg.api.Node;
import dev.chpg.pg.api.NodeSet;

/**
 * A mutable collection for managing distinct {@link GlobalNode} objects.
 * <p>
 * <b>What it represents:</b> A concrete, materialized implementation of {@code NodeSet} specifically tied to the `pg-global` ecosystem.
 * <p>
 * <b>Why it exists:</b> It provides standard HashSet performance and Java Collections compatibility while enforcing strict module guardrails that actively reject node contamination from other engines (e.g., Ephemeral or Universe).
 * <p>
 * <b>When to use it:</b> Use this when accumulating, filtering, or merging arbitrary nodes generated by a {@code GlobalGraph}.
 * <p>
 * <b>Common usage patterns:</b> It is used internally to back results for algebraic traversals (like union or intersection) or manually by developers to group elements before feeding them into algorithms.
 * <p>
 * <b>Important invariants:</b> The set actively blocks any non-{@code GlobalNode} from being added, throwing an {@code IllegalArgumentException}. Query operations (like contains or remove) safely ignore foreign node types and return false.
 * <p>
 * <b>Thread safety:</b> Not thread-safe. Synchronization is required for concurrent access where at least one thread modifies the set.
 * <p>
 * <b>Performance characteristics:</b> The underlying storage is a standard JDK HashSet, meaning insertions and lookups operate in O(1) amortized time, but involve object-allocation overhead not present in purely bitwise or array-backed counterparts.
 */
public final class GlobalNodeSet implements NodeSet {

    private final HashSet<GlobalNode> internalSet;
    private boolean isImmutable = false;

    /**
     * Constructs a new, empty {@code GlobalNodeSet}.
     */
    public GlobalNodeSet() {
        this.internalSet = new HashSet<>();
    }

    /**
     * Constructs a new {@code GlobalNodeSet} containing the specified node.
     *
     * @param initialNode the single node to initially add
     */
    public GlobalNodeSet(Node initialNode) {
        this();
        add(initialNode);
    }

    /**
     * Constructs a new {@code GlobalNodeSet} containing the specified nodes.
     *
     * @param initialNodes an array of nodes to initially add
     */
    public GlobalNodeSet(Node... initialNodes) {
        Objects.requireNonNull(initialNodes, "Node array cannot be null");
        this.internalSet = new HashSet<>((int) (initialNodes.length / 0.75f) + 1);
        for (Node node : initialNodes) {
            add(node);
        }
    }

    /**
     * Constructs a new {@code GlobalNodeSet} containing the elements of the specified collection.
     *
     * @param initialNodes a collection of nodes to initially add
     */
    public GlobalNodeSet(Collection<Node> initialNodes) {
        this();
        Objects.requireNonNull(initialNodes, "Node collection cannot be null");
        addAll(initialNodes);
    }

    GlobalNodeSet asSealed() {
        this.isImmutable = true;
        return this;
    }

    private GlobalNode validate(Node node) {
        Objects.requireNonNull(node, "Node cannot be null");
        if (!(node instanceof GlobalNode impl)) {
            throw new IllegalArgumentException(
                "Cross-graph contamination: Expected GlobalNode, got " + node.getClass().getSimpleName()
            );
        }
        return impl;
    }

    @Override
    public NodeSet toImmutable() {
        if (isImmutable) { return this; }
        if (internalSet.isEmpty()) { return NodeSet.empty(); }
        return new GlobalNodeSet(this).asSealed();
    }

    @Override
    public Optional<Node> one() {
        if (internalSet.isEmpty()) { return Optional.empty(); }
        return Optional.of(internalSet.iterator().next());
    }

    @Override
    public NodeSet intersect(Collection<? extends Node> other) {
        GlobalNodeSet result = new GlobalNodeSet();
        if (other == null || other.isEmpty()) {
            return result.isEmpty() ? NodeSet.empty() : result.asSealed();
        }
        for (GlobalNode node : internalSet) {
            if (other.contains(node)) {
                result.internalSet.add(node);
            }
        }
        return result.isEmpty() ? NodeSet.empty() : result.asSealed();
    }

    @Override
    public NodeSet difference(Collection<? extends Node> other) {
        GlobalNodeSet result = new GlobalNodeSet();
        for (GlobalNode node : internalSet) {
            if (other == null || !other.contains(node)) {
                result.internalSet.add(node);
            }
        }
        return result.isEmpty() ? NodeSet.empty() : result.asSealed();
    }

    @Override
    public NodeSet union(Collection<? extends Node> other) {
        GlobalNodeSet result = new GlobalNodeSet();
        result.internalSet.addAll(this.internalSet);
        if (other != null) {
            for (Node n : other) {
                if (n instanceof GlobalNode gn) {
                    result.internalSet.add(gn);
                }
            }
        }
        return result.isEmpty() ? NodeSet.empty() : result.asSealed();
    }

    @Override
    public Set<Integer> ids() {
        Set<Integer> ids = new HashSet<>((int) (internalSet.size() / 0.75f) + 1);
        for (GlobalNode node : internalSet) {
            ids.add(node.id());
        }
        return ids;
    }

    @Override
    public int[] toIdArray() {
        int[] result = new int[internalSet.size()];
        int i = 0;
        for (Node node : internalSet) {
            result[i++] = node.id();
        }
        return result;
    }

    @Override
    public boolean add(Node node) {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        return internalSet.add(validate(node));
    }

    @Override
    public boolean contains(Object obj) {
        if (!(obj instanceof Node node)) { return false; }
        try {
            return internalSet.contains(validate(node));
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    @Override
    public boolean remove(Object obj) {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        if (!(obj instanceof Node node)) { return false; }
        try {
            return internalSet.remove(validate(node));
        } catch (IllegalArgumentException e) {
            return false;
        }
    }
    @Override
public boolean isMaterialized() {
        return true;
    }

    public int size() {
        return internalSet.size();
    }

    @Override
    public boolean isEmpty() {
        return internalSet.isEmpty();
    }

    @Override
    public void clear() {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        internalSet.clear();
    }

    @SuppressWarnings("unchecked")
    @Override
    public Iterator<Node> iterator() {
        if (isImmutable) {
            return new Iterator<Node>() {
                private final Iterator<GlobalNode> it = internalSet.iterator();
                @Override public boolean hasNext() { return it.hasNext(); }
                @Override public Node next() { return it.next(); }
                @Override public void remove() { throw new UnsupportedOperationException("Collection is unmodifiable"); }
            };
        }
        return (Iterator<Node>) (Iterator<?>) internalSet.iterator();
    }

    @Override
    public Object[] toArray() {
        return internalSet.toArray();
    }

    @Override
    public <T> T[] toArray(T[] a) {
        return internalSet.toArray(a);
    }

    @Override
    public boolean containsAll(Collection<?> c) {
        Objects.requireNonNull(c);
        for (Object obj : c) {
            if (!contains(obj)) {
                return false;
            }
        }
        return true;
    }

    @Override
    public boolean addAll(Collection<? extends Node> c) {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        Objects.requireNonNull(c, "Node collection cannot be null");
        for (Node e : c) {
            validate(e);
        }
        boolean modified = false;
        for (Node e : c) {
            modified |= internalSet.add((GlobalNode) e);
        }
        return modified;
    }

    @Override
    public boolean retainAll(Collection<?> c) {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        Objects.requireNonNull(c);
        boolean modified = false;
        Iterator<GlobalNode> it = internalSet.iterator();
        while (it.hasNext()) {
            if (!c.contains(it.next())) {
                it.remove();
                modified = true;
            }
        }
        return modified;
    }

    @Override
    public boolean removeAll(Collection<?> c) {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        Objects.requireNonNull(c);
        boolean modified = false;
        for (Object obj : c) {
            modified |= this.remove(obj);
        }
        return modified;
    }

    @Override
    public boolean removeIf(java.util.function.Predicate<? super Node> filter) {
        if (isImmutable) { throw new UnsupportedOperationException("Collection is unmodifiable"); }
        return internalSet.removeIf(filter);
    }

    @Override
    public String toString() {
        String joined = internalSet.stream()
                .map(Object::toString)
                .collect(Collectors.joining(", ", "[", "]"));
        return "GlobalNodeSet [nodes=" + joined + "]";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        // Standard Java semantics: safely compares sizes and elements,
        // evaluating to true for empty sets of different types,
        // while deferring to elements for populated sets.
        return internalSet.equals(o);
    }

    @Override
    public int hashCode() {
        return internalSet.hashCode();
    }
}
